### ISSUE TITLE
比较关心mixer后续的进展

### ISSUE THREAD

**Issue by dongzerun** [siddontang/mixer#30]
现在mixer后续有什么进展么？ 我是赶集网的，我打算测测，如果有可能可以测试环境搞搞。

我也是一个go爱好者，最近在学习mixer和 codis代码，codis预计年中会应用在生产线上。

mysql方面蛮喜欢mixer，赶集的体量也比较大，真心希望这个项目能做起来 ~~

**Comment by siddontang** [comment]
你好，豌豆荚基于mixer做了一个这个，https://github.com/wandoulabs/cm 已经用于生产环境中了，你可以试试。

mixer这个个人精力现在实在有限，而且没人帮忙，加之我现在的重点在于ledisdb的cluster，所以没时间弄这个。

**Comment by dongzerun** [comment]
好的 谢谢了，看ledisdb代码学到不少干货。

**Comment by siddontang** [comment]
:smile: 

你也可以关注我这个https://github.com/siddontang/go-mysql，现在我的很多mysql的东西都放到这个repository里面了。

**Comment by dongzerun** [comment]
必须关注啊。我觉得go-mysql更有想象力，可以做成golang版的canal做数据异构。并且基于go-mysql，可以完成mixer的数据resharding，多维度sharding和小表广播。

**Comment by siddontang** [comment]
我对go-mysql的定位是一些基础工具集，主要几个
1，replication相关，这几天在实现facebook里面那个[semi sync mysqlbinlog](http://yoshinorimatsunobu.blogspot.com/2014/04/semi-synchronous-replication-at-facebook.html) ，这样同步数据更及时，然后我已经实现了一个go-mysql-elasticsearch用来更新es，后续会提供抽象的syncer package，跟canal的原理其实差不多了
2，client和proxy相关，做好了到时候在改造mixer，豌豆荚那边其实现在也只是将其作为单纯的proxy然后做读写分离，其实很多当时我们设想的分布式mysql集群的东西根本用不上，而且要做好难度太大，所以后续我也不准备考虑这个了。
3，failover相关，不过如果MHA用好了我就不考虑继续了。
